export const FILE_ICON_TYPE: { [key: string]: string } = {
  // 视频类
  mp4: 'file-video',
  mkv: 'file-video',
  avi: 'file-video',
  flv: 'file-video',
  mov: 'file-video',
  wmv: 'file-video',
  // 音频类
  mp3: 'file-music',
  wav: 'file-music',
  ogg: 'file-music',
  m4a: 'file-music',
  // 图片类
  svg: 'file-image',
  png: 'file-image',
  jpg: 'file-image',
  jpeg: 'file-image',
  gif: 'file-image',
  bmp: 'file-image',
  webp: 'file-image',
  tiff: 'file-image',
  // 表格类
  xls: 'file-excel',
  xlsx: 'file-excel',
  csv: 'file-excel',
  // 文档类
  txt: 'file-document',
  odt: 'file-document',
  rtf: 'file-document',
  doc: 'file-word',
  docx: 'file-word',
  pdf: 'file-powerpoint',
  // 幻灯片类
  ppt: 'file-eye',
  pptx: 'file-eye',
  // 链接类
  url: 'file-link',
  // 压缩文件类
  zip: 'folder-zip',
  rar: 'folder-zip',
  '7z': 'folder-zip',
  tar: 'folder-zip',
  gz: 'folder-zip',
  bz2: 'folder-zip',
  // 文件夹类
  folder: 'folder',
  'folder-size': 'folder-file',
  // 代码类
  js: 'language-javascript',
  ts: 'language-typescript',
  css: 'language-css3',
  html: 'language-html5',
  php: 'language-php',
  java: 'language-java',
  go: 'language-go',
  f90: 'language-fortran',
  c: 'language-c',
  kt: 'language-kotlin',
  md: 'language-markdown',
  cpp: 'language-cpp',
  'c#': 'language-csharp',
  lua: 'language-lua',
  xaml: 'language-xaml',
  py: 'language-python',
  r: 'language-r',
  rb: 'language-ruby',
  rs: 'language-rust',
  swift: 'language-swift',
  // 数据类
  json: 'code-json',
  xml: 'xml',
  sql: 'database',
  default: 'file-cloud',
  // 程序类
  bat: 'powershell',
  sh: 'powershell',
  exe: 'application'
}
