// 定义文件类型的枚举
export enum FileType {
  Video = 'Video',
  Music = 'Music',
  Image = 'Image',
  Excel = 'Excel',
  Document = 'Document',
  Word = 'Word',
  PowerPoint = 'PowerPoint',
  Slide = 'Slide',
  Link = 'Link',
  Zip = 'Zip',
  Folder = 'Folder',
  FolderFile = 'FolderFile',
  Code = 'Code',
  JSON = 'JSON',
  XML = 'XML',
  SQL = 'SQL',
  Default = 'Default',
  Bat = 'Bat',
  PowerShell = 'PowerShell',
  Application = 'Application',
  Media = 'Media',
  Ghost = 'Ghost',
  All = 'All'
}
